#!/bin/bash

#git@github.com:jwu-sym/govtrade.git
cd /data/source/govtrade
source venv/bin/activate
export FLASK_APP=src/app.py
nohup flask run --port 1234 --host 0.0.0.0 --debug &> ./logs/govtrade.log &
